### ISSUE TITLE
Syntax highlight didn't work here

### ISSUE THREAD

**Issue by leonardofl** [martindb/vscode-natural#3]
![Captura de tela de 2022-06-21 09-50-34](https://user-images.githubusercontent.com/362813/174804258-50d952e4-def3-4d35-a768-f8a3bf8fc895.png)

![Captura de tela de 2022-06-21 09-53-04](https://user-images.githubusercontent.com/362813/174804273-6f71b6f5-288a-48ec-bf55-5215cc91d33c.png)

![Captura de tela de 2022-06-21 09-53-34](https://user-images.githubusercontent.com/362813/174804276-02b66962-f27d-4a79-a06f-0421577c1c99.png)

Is this behavior expected?

Thank you

**Comment by leonardofl** [comment]
Obs: I updated my VSCode and it still doen't work.

![Captura de tela de 2022-06-21 10-04-44](https://user-images.githubusercontent.com/362813/174806250-3ad88f97-a6b3-4b7e-a596-5e79a91e47bc.png)

![Captura de tela de 2022-06-21 10-04-36](https://user-images.githubusercontent.com/362813/174806259-52e263ac-e9e3-4b1b-acce-b16cec268863.png)

**Comment by leonardofl** [comment]
Obs: with the option "new text file", VSCode asks for selecting language, and then selecting "natural", it works. But it's not working for already existing files. Maybe some problem with the association of file extension?

**Comment by leonardofl** [comment]
Ah! This did the trick:
![Captura de tela de 2022-06-21 10-31-50](https://user-images.githubusercontent.com/362813/174812101-cc9435aa-247d-4a03-8c22-cd860ca1174a.png)

**Comment by leonardofl** [comment]
Pull request for addressing this issue: https://github.com/martindb/vscode-natural/pull/4

**Comment by martindb** [comment]
Hi Leonardo, it's strange, as the package.json has the file extensions defined as referenced by Microsoft documentation. This should be enought to link the SAG Natural files to the extension.
I've tested it in Windows..... but not in Linux... let me do some checks.

**Comment by leonardofl** [comment]
Tks @martindb!
